# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.1.0

definitions:
          caches:
            npm: ~/.npm

pipelines:
  default:
    - step:
        caches:
          - npm
          - node
        script:
          - cp src/config/config.tpl.js src/config/config.js
          - sed -i 's/{{ globalnamespace }}/MultimediaObjectEditor/g' src/config/config.js
          - sed -i 's/{{ namespace }}/_s4mConfig/g' src/config/config.js
          - sed -i 's/{{ container }}/scene/g' src/config/config.js
          - git submodule init
          - git submodule update --recursive
          - npm install
          - npm test
