export default {
  Atoms: {
    block: 'div',
    div: 'div',
    header: 'header',
    footer: 'footer',
    aside: 'aside',
    article: 'article',
    main: 'main',
    nav: 'nav',
    navigation: 'nav',
    span: 'span',
    text: 'p',
    p: 'p',
    paragraphe: 'p',
    'ulist-container': 'ul',
    ulist: 'ul',
    ul: 'ul',
    'unordered-list': 'ul',
    'olist-container': 'ol',
    olist: 'ol',
    ol: 'ol',
    'ordered-list': 'ol',
    'list-element': 'li',
    li: 'li',
    code: 'pre',
    pre: 'pre',
    input: 'input',
    textarea: 'textarea',
    form: 'form',
    image: 'img',
    img: 'img',
    button: 'button',
    iframe: 'iframe',
    video: 'video',
    canvas: 'canvas',
    audio: 'audio',
  },
  regex: {
    DOMEvent: new RegExp('^(click|mousedown|mouseup|mousemove|change|touchstart|touchmove|touchend|input|focus|dlclick|mouseenter|mouseleave|mouseover|mouseout|blur|search|submit|play|pause|canplay|progress)$'),
    unitProp: new RegExp('position|background|display|visibility|opacity|scale|transform-origin|font-weight|line-height|letter-spacing|z-index|outline|text-align|skew|rotate|transform|overflow|border-style|border-color|word', 'ig'),
    animatableProps: new RegExp('^(background-color|translate|scale|rotate|skew|margin|padding|top|left|right|bottom|color|font-size|width|height|opacity)$'),
    styleProperties: new RegExp('^(background-image|background-position|background-size|background-repeat|position|font-family|display|flex|margin|padding|text-align|outline|list-style|list-decoration|text-transform|text-decoration|zIndex)$'),
  },
  sets: {
    pxProperties: 'marginTop,margin-top,marginLeft,margin-left,marginBottom,margin-bottom,marginRight,margin-right,paddingTop,padding-top,paddingLeft,padding-left,paddingBottom,padding-bottom,paddingRight,padding-right,top,left,bottom,right,translateX,translate-x,translateY,translate-y,translateZ,translate-z,perspectiveX,perspectiveY,perspectiveZ,perspective-x,perspective-y,perspective-z,skew,skewX,skewY,skewZ,skew-x,skew-y,skew-z,width,height,maxWidth,max-width,maxHeight,max-height,minWidth,min-width,minHeight,min-height,borderRadius,border-radius',
    degProperties: 'rotate,rotateX,rotateY,rotateZ',
    transformProperties: 'translate,translateX,translateY,translateZ,translateX,translate-x,translateY,translate-y,translateZ,translate-z,scale,scaleX,scaleY,scaleZ,scale-x,scale-y,scale-z,rotate,rotateX,rotateY,rotateZ,rotate-x,rotate-y,rotate-z,skew,skewX,skewY,skewZ,skew-x,skew-y,skew-z,perspective,perspectiveX,perspectiveY,perspectiveZ,perspective-x,perspective-y,perspective-z',
    styleProperties: 'opacity,z-index',
  },
};
