const data = () => ({
  Atoms: {
    block: "div",
    div: "div",
    header: "header",
    footer: "footer",
    aside: "aside",
    article: "article",
    main: "main",
    nav: "nav",
    navigation: "nav",
    span: "span",
    text: "p",
    p: "p",
    paragraphe: "p",
    "ulist-container": "ul",
    ulist: "ul",
    ul: "ul",
    "unordered-list": "ul",
    "olist-container": "ol",
    olist: "ol",
    ol: "ol",
    "ordered-list": "ol",
    "list-element": "li",
    li: "li",
    code: "pre",
    pre: "pre",
    input: "input",
    textarea: "textarea",
    form: "form",
    image: "img",
    img: "img",
    button: "button",
    iframe: "iframe",
    video: "video",
    canvas: "canvas",
    audio: "audio",
  },
  regex: {
    DOMEvent: new RegExp("^(click|mousedown|mouseup|mousemove|change|touchstart|touchmove|touchend|input|focus|dlclick|mouseenter|mouseleave|mouseover|mouseout|blur|search|submit|play|pause|canplay|progress)$"),
    unitProp: new RegExp("position|background|display|visibility|opacity|scale|transform-origin|font-weight|line-height|letter-spacing|z-index|outline|text-align|skew|rotate|transform|overflow|border-style|border-color|word", "ig"),
    animatableProps: new RegExp("^(background-color|translate|scale|rotate|skew|margin|padding|top|left|right|bottom|color|font-size|width|height|opacity)$"),
  },
  sets: {
    pxProperties: "marginTop,margin-top,marginLeft,margin-left,marginBottom,margin-bottom,marginRight,margin-right,paddingTop,padding-top,paddingLeft,padding-left,paddingBottom,padding-bottom,paddingRight,padding-right,top,left,bottom,right,translateX,translateY,translateZ,perspectiveX,perspectiveY,perspectiveZ,width,height,maxWidth,maxHeight,minWidth,minHeight,borderRadius",
    degProperties: "rotate,rotateX,rotateY,rotateZ,skew,skewX,skewY,skewZ",
    transformProperties: "translate,translateX,translateY,translateZ,scale,scaleX,scaleY,scaleZ,rotate,rotateX,rotateY,rotateZ,rotateC,rotateCX,rotateCY,skew,skewX,skewY,skewZ,perspective",
    styleProperties: "opacity,z-index",
  },
});
